### PR TITLE
Update TagSeeder.php

### PR DESCRIPTION
**Pull request by FrankOgiamien**
Canadian brands added G-L

### CODE REVIEW

**Comment by GeniJaho** [comment]
There are some commas missing after tag names, causing the script to break. Can you add them please? Otherwise I can add them, no problem. They're highlighted in orange when there's a comma missing.

**Comment by woodforthetrees** [comment]
> There are some commas missing after tag names, causing the script to break. Can you add them please? Otherwise I can add them, no problem. They're highlighted in orange when there's a comma missing.

I can do that now - they seem to be my missing comma's from #17

**Review by woodforthetrees — COMMENTED** [review]
added missing commas and committed changes to canadian-brands-part-2. 
Here's hoping that's correct.

**Comment by FrankOgiamien** [comment]
Thank you! Sorry for my sloppiness.

**Pull request merged**
